version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - ./server/.env
    restart: always
    ports:
      - 8000:8000
    networks:
      - formula1_network
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - formula1_network

networks:
  formula1_network:
    driver: bridge
