version: '3.8'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - ./server/.env
    restart: always
    ports:
      - 8000:8000
    networks:
      - app_network
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    env_file:
      - ./client/.env
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
