version: '3.8'
services:
  server:
    container_name: f1-server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 8000:8000
    networks:
      - formula1
  client:
    container_name: f1-client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - server
    networks:
      - formula1

networks:
  formula1:
    driver: bridge
