version: '3.8'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - DATABASE_URL=file:./database.db
      - CLIENT_URL=http://client:80
    restart: always
    ports:
      - 8000:8000
    networks:
      - app_network
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      - VITE_APP_SERVER_URL=http://server:8000
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
